### ISSUE TITLE
Atom 0.187.0+ complains "Failed to load the language-review package"

### ISSUE THREAD

**Issue by muojp** [vvakame/language-review#10]
1. Update Atom to 0.187.0 using auto updater
2. Restart Atom

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [language-review](https://github.com/vvakame/language-review) package, v0.6.4

### Stack Trace

Failed to load the language-review package

```
At Module version mismatch. Expected 41, got 16.

Error: Module version mismatch. Expected 41, got 16.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/keinakazawa/.atom/packages/language-review/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/keinakazawa/.atom/packages/language-review/node_modules/pathwatcher/lib/main.js:207:4)
    at Module._compile (module.js:475:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
japanese-wrap, v0.2.3
language-review, v0.6.4
vim-mode, v0.36.0

# Dev
No dev packages
```

**Comment by muojp** [comment]
@vvakame :cry:

**Comment by vvakame** [comment]
@muojp :crying_cat_face:

**Comment by vvakame** [comment]
@muojp fix it!(maybe

**Comment by muojp** [comment]
language-reviewのmasterで久々に出た

**Comment by muojp** [comment]
1. language-reviewの開発版を有効にした状態でAtomを開く
2. 前回開いていた大量のタブが復帰され、以下の例外が捕捉される

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4
**Thrown From**: [language-review](https://github.com/vvakame/language-review) package, v0.8.10


### Stack Trace

Failed to load the language-review package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/muo/workspace/language-review/lib/util/review-runner.js:9:78)
    at /Users/muo/workspace/language-review/lib/util/review-runner.js:19:5
    at Object.<anonymous> (/Users/muo/workspace/language-review/lib/util/review-runner.js:33:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:163:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/muo/workspace/language-review/lib/linter.js:3:20)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "language-review": {}
}
```

### Installed Packages

```coffee
# User
japanese-wrap, v0.2.10
language-review, v0.8.10
linter, v0.12.6
vim-mode, v0.50.0

# Dev
No dev packages
```

**Comment by muojp** [comment]
なお、15ファイルほど`.re`を開いているのだけど 閉じたら開き直すのが割と大変なのでどのファイルが原因かは特定してない

**Comment by muojp** [comment]
この状態では、かどうかは分からないけれどToggle Preview / Toggle Outline / Toggle Syntax Listが全て効かない(ショートカット、メニュー共に)

**Comment by muojp** [comment]
あれ、already reportedってAtom内で言われたけど ちゃんと見ると別の問題ですね

**Comment by muojp** [comment]
手元で試したこと

 - 依存関係更新後の`grunt setup`をサボった分かな?→実行した
 - language-reviewのディレクトリで`grunt`してビルド→
 - `apm rebuild`忘れてた分かな?→実行した
 - 手元のreview.jsツリー古い分かな?→一応最新へ上げた(けれどlanguage-reviewのビルドではnpmからreview.jsの新版拾ってくるはずなので関係なさそう)
 - あ、手元のTypeScript、1.5.0betaだ→`npm update -g typescript`で1.5.3へアップデート
 - ん、language-reviewを`grunt`でビルドする際にひとつ上の階層のreview.js参照してる。先にこっちのビルドを試そう→gruntでのビルドにて以下のエラーを吐く

```
Using tsc v1.5.3
/Users/muo/workspace/review.js/lib/builder/htmlBuilder.ts(351,45): error TS2339: Property 'trimLeft' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/builder/htmlBuilder.ts(406,56): error TS2339: Property 'trimLeft' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/builder/textBuilder.ts(254,45): error TS2339: Property 'trimLeft' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/builder/textBuilder.ts(296,56): error TS2339: Property 'trimLeft' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/controller/config.ts(151,26): error TS2339: Property 'error' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/controller/config.ts(153,27): error TS2339: Property 'warn' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/controller/config.ts(155,26): error TS2339: Property 'info' does not exist on type 'string'.
/Users/muo/workspace/review.js/lib/controller/controller.ts(1,1): error TS6053: File '/Users/muo/workspace/review.js/lib/typings/custom-colors.d.ts' not found.
/Users/muo/workspace/review.js/lib/index.ts(4,1): error TS6053: File '/Users/muo/workspace/review.js/lib/typings/polyfill.d.ts' not found.
/Users/muo/workspace/review.js/lib/js/exception.ts(2,14): error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Specify '--experimentalDecorators' to remove this warning.
```

 - なんかreview.js環境自体を壊してるっぽい?ひとまず作りなおそう→`git clean -dfx`叩いて`./setup.sh`→`grunt` → 上と同じエラー
 - 使ってるNode.jsがさすがに古い?→一応io.jsの1.6.4も入ってたけど気にせずio.jsの最新版にしてみる→`nodebrew install-binary io@3`→`nodebrew use io@3`→`npm install -g grunt-cli`→`./setup.sh`(警告大量に出る感じを見ると、さすがに新しくしすぎたっぽい?)→`grunt`→さきと同じエラー

で諦めましたん

**Comment by muojp** [comment]
↑
```
review.js muo$ git log --abbrev-commit | head -1
commit 00d3f13

language-review muo$ git log --abbrev-commit | head -1
commit 7847a3a
```

**Comment by muojp** [comment]
その後、review.js側のビルドエラーは一旦諦めておくとして、やっぱlanguage-reviewのビルドからひとつ上の階層のreview.jsを参照してるのがおかしいなーと思う。

 - review.jsとlanguage-reviewを以前同時にいじってた時の動作確認用に設定したような気がしたので、language-review側も`git clean -dfx`を叩き、`setup.sh`でひと通りの準備からビルドまでを実施

結果、ビルドは通り Atom側でも例外解消した。

review.jsのビルドが通らないのをさておくと、手元開発環境の再構築で解消しましたとさ(closed)

**Comment by vvakame** [comment]
language-review側は問題ないってことだな！
