### ISSUE TITLE
Cのコンパイラ環境が不足しているとlanguage-reviewのインストールエラーが起こる？

### ISSUE THREAD

**Issue by tacksman** [vvakame/language-review#41]
windows 7にatomをインストールして、apm install language-reviewしたところ、インストールエラーになりました。
```
> runas@3.1.1 install C:\Users\altacks\AppData\Local\Temp\apm-install-dir-1151012-7572-1qhzbqr\node_modules\language-review\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild


C:\Users\altacks\AppData\Local\Temp\apm-install-dir-1151012-7572-1qhzbqr\node_modules\language-review\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\altacks\AppData\Local\atom\app-1.1.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
���̃\�����[�V�������̃v���W�F�N�g�� 1 �x�� 1 ���r���h���܂��B���s�r���h���L���ɂ����ɂ́A"/m" �X�C�b�`���ǉ����Ă��������B
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(54,5): error MSB8020: The build tools for Visual Studio 2012 (Platform Toolset = 'v110') cannot be found. To build using the v110 build tools, please install Visual Studio 2012 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\altacks\AppData\Local\Temp\apm-install-dir-1151012-7572-1qhzbqr\node_modules\language-review\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\altacks\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\altacks\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\altacks\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\altacks\\.atom\\.apmrc" "install" "C:\\Users\\altacks\\AppData\\Local\\Temp\\d-1151012-7572-sy3t9x\\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
```

関係ありそうな導入済みの開発環境としては、 Python 2.7.10、node v4.2.2、npm 2.14.7あたりです。

**Comment by vvakame** [comment]
C bindingがビルドできなくて落ちてるなー。
適当なディレクトリで `npm init` してEnter連打して `npm install pathwatcher` 実行してみてくれる？

**Comment by tacksman** [comment]
こんな感じで失敗しました
```
npm WARN package.json altacks@1.0.0 No description
npm WARN package.json altacks@1.0.0 No repository field.
npm WARN package.json altacks@1.0.0 No README data
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "pathwather"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/pathwat
her
npm ERR! 404
npm ERR! 404 'pathwather' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

npm ERR! 404 It was specified as a dependency of 'altacks'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\altacks\npm-debug.log
```

**Comment by vvakame** [comment]
おうエラーメッセージちょっと読んでtypoってるなーくらいは気がつくんだよォ

**Comment by vvakame** [comment]
Python 2.7系とVisualStudioが必要とか書いてあるなー…。やばい。

**Comment by tacksman** [comment]
ｷﾞｬｰｽ
現実はこっちでした
```
npm WARN package.json altacks@1.0.0 No description
npm WARN package.json altacks@1.0.0 No repository field.
npm WARN package.json altacks@1.0.0 No README data

> runas@3.1.1 install C:\Users\altacks\node_modules\pathwatcher\node_modules\run
as
> node-gyp rebuild


C:\Users\altacks\node_modules\pathwatcher\node_modules\runas>if not defined npm_
config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

このソリューション内のプロジェクトを 1 度に 1 つずつビルドします。並行ビルドを有
効にするには、"/m" スイッチを追加してください。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targe
ts(366,5): warning MSB8003: Could not find WindowsSDKDir variable from the regi
stry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versi
on number. [C:\Users\altacks\node_modules\pathwatcher\node_modules\runas\build\
runas.vcxproj]
TRACKER : error TRK0005: 検索できませんでした: "CL.exe"。指定されたファイルが見
つかりません。 [C:\Users\alta
cks\node_modules\pathwatcher\node_modules\runas\build\runas.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\altacks\node_modules\pathwatcher\node_modules\runas
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "pathwatcher"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\altacks\npm-debug.log
```

**Comment by vvakame** [comment]
https://github.com/vvakame/language-review/commit/ce05823d98096f1c73c7165c267f0f045eed5988
ひも付け損ねた…。
Windowsでpathwatcher配下のrunasがビルドできないようなのでpathwatcherを外す対応を入れた…！

**Comment by vvakame** [comment]
インスコできたらしい。
