### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deactivate' of undefined

### ISSUE THREAD

**Issue by vvakame** [vvakame/language-review#51]
1. Preview開く
2. Atom再起動
3. Preview真っ白 閉じると発生

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [language-review](https://github.com/vvakame/language-review) package, v0.12.4

### Stack Trace

Uncaught TypeError: Cannot read property 'deactivate' of undefined

```
At /Users/vvakame/.atom/packages/language-review/lib/view/review-preview-view.js:80

TypeError: Cannot read property 'deactivate' of undefined
    at ReVIEWPreviewView.destroy (/Users/vvakame/.atom/packages/language-review/lib/view/review-preview-view.js:80:20)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:451:18)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:695:17)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "language-review": {
    "config": {
      "debug": {}
    },
    "debug": true
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.12.0
language-review, v0.12.4
linter, v1.11.2
minimap, v4.16.2
redpen, v0.3.5

# Dev
No dev packages
```

**Comment by vvakame** [comment]
再現しなくなってた…(Preview出して閉じて開いてもPreviewが開いてない状態になるようになった
