### ISSUE TITLE
インストール後、プレビューを開始するとエラー発生

### ISSUE THREAD

**Issue by kuy** [vvakame/language-review#54]
1. language-reviewをインストール
2. Packages > Re:VIEW > Toggle Preview
3. エラー発生の赤い通知が表示される

以下、表示されたエラー通知の内容をコピーするボタンを押して取得したものです。

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [language-review](https://github.com/vvakame/language-review) package, v0.12.6

### Stack Trace

Uncaught TypeError: Cannot read property 'getParent' of null

```
At /Users/kodama/.atom/packages/language-review/lib/util/review-runner.js:100

TypeError: Cannot read property 'getParent' of null
    at /Users/kodama/.atom/packages/language-review/lib/util/review-runner.js:100:56
```

### Commands

```
     -2:18.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:18 core:cut (atom-text-editor.editor.mini.is-focused)
     -2:16.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:28.8.0 application:new-file (atom-pane.pane.active)
  8x -0:19.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:16 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.2.0 grammar-selector:show (atom-text-editor.editor)
     -0:01.1.0 language-review:toggle-preview (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-review, v0.12.6
linter, v1.11.4

# Dev
No dev packages
```

**Comment by kuy** [comment]
Atomを再起動したあと、再度プレビューを実行すると別のエラーが発生しているので貼っておきます。

**Atom Version**: 1.7.1
**System**: Mac OS X 10.11.4
**Thrown From**: [language-review](https://github.com/vvakame/language-review) package, v0.12.6


### Stack Trace

Uncaught TypeError: Cannot read property 'deactivate' of undefined

```
At /Users/kodama/.atom/packages/language-review/lib/view/review-preview-view.js:81

TypeError: Cannot read property 'deactivate' of undefined
    at ReVIEWPreviewView.destroy (/Users/kodama/.atom/packages/language-review/lib/view/review-preview-view.js:81:20)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:639:18)
    at Controller.togglePreview (/Users/kodama/.atom/packages/language-review/lib/language-review.js:95:25)
    at atom-workspace.<anonymous> (/Users/kodama/.atom/packages/language-review/lib/language-review.js:54:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:314:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -0:00.7.0 language-review:toggle-preview (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-review, v0.12.6
linter, v1.11.4

# Dev
No dev packages
```

**Comment by vvakame** [comment]
ありがとうございます！見てみますー。

**Comment by vvakame** [comment]
着手して調べ始めてみてますが再現しなくなってしまっている…。

**Comment by vvakame** [comment]
b97b113914114fccac22df3e97656ee14cec3619 ざっくりした対処を入れてみました…。
再発してから考える。

**Comment by kuy** [comment]
ご対応ありがとうございます。
こちらの環境でも改めて起動してみたらもうエラーが出なくなっていました。
