### ISSUE TITLE
Uncaught Error: editor is required

### ISSUE THREAD

**Issue by StudioQuad9** [vvakame/language-review#69]
動作のテストをしていてこの問題が起こりました。
プルダウンメニュー[パッケージ/Re:VIEW/ToggleOutline]を選択しても動作に変化はありませんでした。
どういった対処が必要でしょうか？
よろしくお願いします。

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.3
**Thrown From**: [language-review](https://github.com/vvakame/language-review) package 0.15.6

### Stack Trace

Uncaught Error: editor is required

```
At /Users/quad9/.atom/packages/language-review/lib/util/review-runner.js:61

Error: editor is required
    at /packages/language-review/lib/util/review-runner.js:61:19)
    at ReVIEWOutlineView.attach (/packages/language-review/lib/view/review-outline-view.js:43:22)
    at ReVIEWOutlineView.toggle (/packages/language-review/lib/view/review-outline-view.js:36:18)
    at Controller.toggleOutline (/packages/language-review/lib/language-review.js:103:26)
    at /packages/language-review/lib/language-review.js:46:19)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350017)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348492)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:694296)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:701680)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -3:12.3.0 markdown-preview:toggle (input.hidden-input)
  2x -2:43 language-review:toggle-outline (div.review-preview.native-key-bindings)
```

### Non-Core Packages

```
atomic-emacs 0.13.0 
busy-signal 2.0.1 
intentions 1.1.5 
japanese-menu 1.14.0 
language-review 0.15.6 
language-vue 0.24.0 
linter 2.3.0 
linter-erb 1.1.3 
linter-ui-default 1.7.1 
multi-cursor 2.1.5 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by vvakame** [comment]
反応遅くてすみません。
僕自身がVSCodeユーザになってしまったので、現在このパッケージはメンテされていません…。
10分くらい環境を最新化できるか見てみたのですがちょっと手間がかかりそうでした。
パッチは受け付けています。(それも反応が遅くなるとは思いますが…)
